### ISSUE TITLE
update for cfbs

### ISSUE THREAD

**Issue by craigcomstock** [nickanderson/cfengine-file_integrity_monitoring#2]
We now have the "directory" build step so I think you can:

- rm def.json
- tag the policy as autorun
```
bundle agent monitor_file_paths_tagged_all_changes
{
  meta:
      "description" string => "Inventory and monitor any filepath tagged with FIM=all_changes";
      "authors" slist => { "Nick Anderson <nick@cmdln.org>" };
      "tags" slist => { "autorun" };
```

- and change the submission to cfbs-index to use the `directory` step command.

```
    "library-file-integrity-monitoring": {
      "description": "Monitor key files for changes",
      "tags": ["wip", "untested"],
      "repo": "https://github.com/nickanderson/cfengine-file_integrity_monitoring",
      "by": "https://github.com/nickanderson",
      "version": "0.1.0",
      "commit": "0fee53540262541c09f17cd8774ffe5ccea48482",
      "steps": [
        "directory ./policy/file_integrity_monitoring/ services/file_integrity_monitoring/"
      ]
    }
```

As this will automatically include the .cf file in the list of autorun inputs and the autorun tag will take care of adding to the bundlesequence.

**Comment by nickanderson** [comment]
I intentionally did not choose to activate this with autorun because the later it is done the more opportunity there is to pick up variables with the tag being looked for.

**Comment by nickanderson** [comment]
I did however make some cfbs related changes to the repo, and you can now add this repo directly.
